# Generated by Django 4.2.6 on 2023-10-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCards', '0005_alter_cards_amount_alter_cards_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
