# Generated by Django 4.2.6 on 2023-11-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCards', '0007_cards_card_number_alter_cards_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='dateTime',
            field=models.DateTimeField(auto_now=True, default=144),
            preserve_default=False,
        ),
    ]
